### ISSUE TITLE
无法获取Token

### ISSUE THREAD

**Issue by Zack9527** [netcookies/Gewe-Notify#1]
Gewechat 后端已经部署成功了，指定ip之后还是显示获取Token失败

**Comment by Zack9527** [comment]
这是命名行访问后端结果
![image](https://github.com/user-attachments/assets/54748fd5-dc64-4dc1-a161-ebbf457aeffd)

**Comment by netcookies** [comment]
你这应该是成功获取到了，你在home assistant 的logger里开下debug，日志贴我看看

**Comment by Zack9527** [comment]
找到问题了，设置页面的bug，输入URL 点提交的时候，焦点不能在输入框里，要切到其他地方，否则读取到的字符串是空

**Comment by netcookies** [comment]
> 找到问题了，设置页面的bug，输入URL 点提交的时候，焦点不能在输入框里，要切到其他地方，否则读取到的字符串是空

居然还有这种bug？？怎么复现告诉我下，我查查看
